aboutblog/urls.py
from django.conf.urls import url
from . import views

app_name = 'aboutblog'
urlpatterns = [
    url(r'^about/$', views.about_page, name='about'),
]

blog/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.ArticleListView.as_view(), name='article_list'),
    url(r'^article/(?P<pk>[0-9]+)/$', views.ArticleDetail.as_view(), name='article_detail'),
    url(r'^article/new/$', views.ArticleCreate.as_view(), name='article_new'),
    url(r'^article/(?P<pk>[0-9]+)/edit/$', views.ArticleUpdate.as_view(), name='article_edit'),
    url(r'^drafts/$', views.DraftArticleListView.as_view(), name='article_draft_list'),
    url(r'^article/(?P<pk>\d+)/publish/$', views.article_publish, name='article_publish'),
    url(r'^article/(?P<pk>\d+)/delete/$', views.ArticleDelete.as_view(), name='article_delete'),
    url(r'^comment/(?P<pk>\d+)/approve/$', views.comment_approve, name='comment_approve'),
    url(r'^comment/(?P<pk>\d+)/remove/$', views.CommentDelete.as_view(), name='comment_remove'),
    url(r'^categories/(?P<categoryName>\w+)/$', views.ArticleListView.as_view(), name='article_categories_list'),
    url(r'^author/(?P<authorName>\w+)/$', views.ArticleListView.as_view(), name='article_author_list'),
    url(r'^search/$', views.SearchArticleListView.as_view(), name='search_list'),
    url(r'^article/(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/$', views.ArticleListView.as_view(), name='article_date_list'),
    url(r'^accounts/register/$', views.RegisterFormView.as_view(), name='register'),
]

myblog/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.contrib.auth import views

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^accounts/login/$', views.login, name='login'),
    url(r'^accounts/logout/$', views.logout, name='logout', kwargs={'next_page': '/'}),
    url(r'', include('blog.urls')),
    url(r'', include('aboutblog.urls')),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.urls import reverse
from ckeditor_uploader.fields import RichTextUploadingField

class Category(models.Model):
    title = models.CharField(max_length=200)
    text = models.TextField()
    urlstext = models.CharField(max_length=20)

    def __str__(self):
        return self.title

class Article(models.Model):
    author = models.ForeignKey('auth.User')
    category = models.ForeignKey('blog.Category')
    title = models.CharField(max_length=200)
    text = RichTextUploadingField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)
    image = models.ImageField(blank=True, upload_to='blog/images/%Y/%m/%d')

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def approved_comments(self):
        return self.comments.filter(approved_comment=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:article_detail', kwargs={'pk': self.pk})

    def was_published_recently(self):
        now = timezone.now()
        if self.published_date:
            return now - datetime.timedelta(days=1) <= self.published_date <= now
        else:
            return False
    was_published_recently.admin_order_field = 'published_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Comment(models.Model):
    article = models.ForeignKey('blog.Article', related_name='comments')
    author = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text

blog/forms.py
from django import forms
from .models import Article, Comment

class ArticleForm(forms.ModelForm):

    class Meta:
        model = Article
        fields = ('title', 'category', 'text', 'image')

    def __init__(self, *args, **kwargs):
        super(ArticleForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({'class' : 'form-control'})
        self.fields['category'].widget.attrs.update({'class' : 'form-control'})
        self.fields['text'].widget.attrs.update({'class' : 'form-control'})
        self.fields['image'].widget.attrs.update({'class' : 'form-control'})


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('author', 'text',)

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.fields['author'].widget.attrs.update({'class' : 'form-control'})
        self.fields['text'].widget.attrs.update({'class' : 'form-control', 'rows' : '10'})

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.utils import timezone
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Article, Comment
from .forms import ArticleForm, CommentForm

from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import FormMixin, DeleteView, CreateView, UpdateView

from django.http import JsonResponse, HttpResponse, HttpResponseNotFound, Http404
from django.core import serializers

from django.utils.html import strip_tags
from django.utils.safestring import mark_safe
from html import unescape
from django.template.defaultfilters import linebreaksbr, truncatechars

from django.views.decorators.vary import vary_on_headers
from json import dumps
from django.db.models import Case, Sum, When, IntegerField

from django.views.generic.edit import FormView
from django.contrib.auth.forms import UserCreationForm

from django.db.models.functions import Length

def ger_articles_page(articles, page, paginate_by = 4):
    paginator = Paginator(articles, paginate_by)
    try:
        articles_page = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        articles_page = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        articles_page = paginator.page(paginator.num_pages)
    return articles_page

class ArticleListView(ListView):
    allow_empty = True
    context_object_name = 'articles'
    model = Article
    paginate_by = 4
    template_name = "blog/article_list.html"

    @method_decorator(vary_on_headers('X-Requested-With'))
    def dispatch(self, *args, **kwargs):
        return super(ArticleListView, self).dispatch(*args, **kwargs)

    def field_json_queryset(self, articles):
        articles = articles.values('id', 'image', 'published_date', 'title', 'text', 'author__username', 'category__urlstext', 'category__title').annotate(approved_comments=Sum(Case(When(comments__approved_comment=True, then=1),default=0,output_field=IntegerField())))
        return articles

    def get_queryset(self):
        articles = Article.objects.filter(published_date__lte=timezone.now())
        articles = articles.order_by('-published_date', 'title')
        categoryName = self.kwargs.get('categoryName', "")
        authorName = self.kwargs.get('authorName', "")

        year = self.kwargs.get('year', "")
        month = self.kwargs.get('month', "")
        day = self.kwargs.get('day', "")

        if categoryName:
            articles = articles.filter(category__urlstext=categoryName)
        elif authorName:
            articles = articles.filter(author__username=authorName)
        elif year and month and day:
            articles = articles.filter(published_date__year=year).filter(published_date__month=month).filter(published_date__day=day)

        return articles

    def get_context_data(self, **kwargs):
        context = super(ArticleListView, self).get_context_data(**kwargs)
        context['mode_list'] = 'simple'
        context['list_article_pag'] = ger_articles_page(self.get_queryset(), self.request.GET.get('page'), self.paginate_by)
        return context

    def render_to_response(self, context, **response_kwargs):
        if self.request.is_ajax():
            mensajes = ger_articles_page(self.field_json_queryset(self.get_queryset()), self.request.GET.get('page'), self.paginate_by)
            json_object_records=[]

            for line in mensajes:
                json_object_dict = {}
                json_object_dict['id'] = line['id']
                json_object_dict['image'] = line['image']
                json_object_dict['published_date'] = line['published_date']
                json_object_dict['text'] = truncatechars(linebreaksbr(strip_tags(unescape(line['text']))),400)
                json_object_dict['title'] = line['title']
                json_object_dict['username'] = line['author__username']
                json_object_dict['category_urlstext'] = line['category__urlstext']
                json_object_dict['category_title'] = line['category__title']
                json_object_dict['approved_comments'] = line['approved_comments']
                json_object_records.append(json_object_dict)

            json_page_records=[]
            json_page_dict = {}
            json_page_dict['has_other_pages'] = mensajes.has_other_pages()
            json_page_dict['has_previous'] = mensajes.has_previous()
            json_page_dict['paginator_page_range'] = mensajes.paginator.page_range[-1]
            json_page_dict['has_next'] = mensajes.has_next()
            json_page_dict['end_index'] = mensajes.end_index()
            json_page_dict['start_index'] = mensajes.start_index()

            cur = 1;
            if (self.request.GET.get('page')):
                try:
                    cur = int(self.request.GET.get('page'))
                except ValueError:
                    cur = 1

            json_page_dict['current_page'] = cur
            json_page_records.append(json_page_dict)

            json_object = {}
            json_object["json_object"]=json_object_records
            json_object["json_page"]=json_page_records
            return JsonResponse(json_object)
        else:
            return super(ArticleListView,self).render_to_response(context, **response_kwargs)



class SearchArticleListView(ListView):
    allow_empty = True
    context_object_name = 'articles'
    model = Article
    paginate_by = 4
    template_name = "blog/article_list.html"

    def __init__(self, **kwargs):
        self.message = ''
        self.srchtxt = ''

    def get_queryset(self):
        if 'srchtxt' in self.request.GET:
            self.message = 'You searched for: %r' % self.request.GET.get('srchtxt', "")
            self.srchtxt = self.request.GET.get('srchtxt', "")
        else:
            self.message = 'You submitted an empty form.'
            self.srchtxt = ''

        articles = ''
        if self.srchtxt:
            articles = Article.objects.filter(published_date__lte=timezone.now())
            articles = articles.order_by('-published_date', 'title')
            articles = articles.filter(text__icontains=self.srchtxt)
        return articles

    def get_context_data(self, **kwargs):
        context = super(SearchArticleListView, self).get_context_data(**kwargs)
        context['mode_list'] = 'search'
        context['list_article_pag'] = ger_articles_page(self.get_queryset(), self.request.GET.get('page'), self.paginate_by)
        context['message'] = self.message
        context['srchtxt'] = self.srchtxt
        return context


@method_decorator(login_required, name='dispatch')
class DraftArticleListView(ListView):
    allow_empty = True
    context_object_name = 'articles'
    model = Article
    paginate_by = 4
    template_name = "blog/article_list.html"

    def get_queryset(self):
        articles = Article.objects.filter(published_date__isnull=True, author__username = self.request.user)
        articles = articles.order_by('-created_date', 'title')
        return articles

    def get_context_data(self, **kwargs):
        context = super(DraftArticleListView, self).get_context_data(**kwargs)
        context['mode_list'] = 'draft'
        context['list_article_pag'] = ger_articles_page(self.get_queryset(), self.request.GET.get('page'), self.paginate_by)
        return context


class ArticleDetail(FormMixin, DetailView):
    context_object_name = 'article'
    model = Article
    template_name = "blog/article_detail.html"
    form_class = CommentForm

    def get_context_data(self, **kwargs):
        context = super(ArticleDetail, self).get_context_data(**kwargs)
        context['form'] = CommentForm(initial={'post': self.object})
        context['comments'] = Comment.objects.filter(article__id=self.object.id).filter(created_date__lte=timezone.now()).order_by('created_date')
        return context

    def get_queryset(self):
        if self.request.user.is_authenticated():
            articles = Article.objects.filter(author__username = self.request.user) | Article.objects.filter(published_date__lte=timezone.now())
        else:
            articles = Article.objects.filter(published_date__lte=timezone.now())
        return articles

    def get_success_url(self):
        return reverse('blog:article_detail', kwargs={'pk': self.object.id})

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.article = self.object
        comment.save()
        return super(ArticleDetail, self).form_valid(form)


@method_decorator(login_required, name='dispatch')
class ArticleDelete(DeleteView):
    model = Article
    template_name = "blog/article_confirm_delete.html"
    success_url = reverse_lazy('blog:article_draft_list')

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()

        if str(self.object.author.username) == str(request.user):
            return super(ArticleDelete, self).dispatch(request, *args, **kwargs)
        else:
            raise Http404


@method_decorator(login_required, name='dispatch')
class ArticleCreate(CreateView):
    model = Article
    template_name = "blog/article_edit.html"
    form_class = ArticleForm

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = self.request.user

blog/templates/blog/article_confirm_delete.html
{% extends 'blog/content.html' %}

{% block place_article %}
  <div class="card my-4">
    <h5 class="card-header">Delete Article:</h5>
    <div class="card-body">
      <form action="" method="post">{% csrf_token %}
        <p>Attention! Only an author can delete an article</p>
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <input type="button" class="btn btn-primary" value="Cancel" onClick="javascript:history.go(-1);">&nbsp;&nbsp;

        <button type="submit" class="btn btn-primary">Confirm</button>
      </form>
    </div>
  </div>
{% endblock place_article %}

blog/templates/blog/article_detail.html
{% extends 'blog/content.html' %}

{% block place_article %}
  <h1 class="mt-4">{{ article.title }}</h1>
  <p class="lead">
    by
    <a href="{% url 'blog:article_author_list' authorName=article.author.username %}">{{ article.author }}</a>
    Categories: <a href="{% url 'blog:article_categories_list' categoryName=article.category.urlstext %}">{{ article.category }}</a>
  </p>
  <hr>

  {% if article.published_date %}
    <div class="date">
      <p>Posted on {{ article.published_date|date:'d-m-Y' }}</p>
    </div>
  {% else %}
    {% if user.is_authenticated %}
      {% if user == article.author %}
        <a class="btn btn-primary" href="{% url 'blog:article_publish' pk=article.pk %}">&nbsp;Publish</a>
      {% else %}
        <p class="text-info">The right to publish only from the author</p>
      {% endif %}
    {% else %}
      <p>No posted</p>
    {% endif %}
  {% endif %}
  <hr>

  {% if article.image %}
    <div class="span2">
      <img  src="{{ MEDIA_URL }}{{ article.image }}">
    </div>
   <hr>
  {% endif %}

  <p>{% autoescape off %}{{ article.text }}{% endautoescape %}</p>
  <hr>

  {% if user.is_authenticated %}
    {% if user == article.author %}
      <a class="btn btn-primary" href="{% url 'blog:article_edit' pk=article.pk %}"><span class="glyphicon glyphicon-pencil">&nbsp;Edit</span></a>
      <a class="btn btn-primary" href="{% url 'blog:article_delete' pk=article.pk %}"><span class="glyphicon glyphicon-remove">&nbsp;Delete</span></a>
      <hr>
    {% endif %}
  {% endif %}

  <div class="card my-4">
    <h5 class="card-header">Leave a Comment:</h5>
    <div class="card-body">
      <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
    </div>
  </div>

  {% for comment in comments %}
    <div class="media mb-4">
      <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
      <div class="media-body">
        {% if not comment.approved_comment %}
          <a class="btn btn-primary" href="{% url 'blog:comment_remove' pk=comment.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
          <a class="btn btn-primary" href="{% url 'blog:comment_approve' pk=comment.pk %}"><span class="glyphicon glyphicon-ok"></span></a>
        {% endif %}
        <h5 class="mt-0">Comment by {{ comment.author }} : {{ comment.created_date|date:'d-m-Y' }}</h5>
        <p>{{ comment.text|linebreaks }}</p>
      </div>
    </div>
    {% empty %}
    <p></p>
  {% endfor %}



{% endblock place_article %}

blog/templates/blog/article_edit.html
{% extends 'blog/content.html' %}

{% block place_article %}
  <div class="card my-4">
    <h5 class="card-header">New Article:</h5>
    <div class="card-body">
      <p>Attention! Only an author can edit an article</p>
      <form method="POST" class="post-form" enctype="multipart/form-data">{% csrf_token %}
        {{ form.non_field_errors }}
        <div class="form-group">
          {{ form.title.errors }}
          <label for="title">Title:</label>
          {{ form.title }}
        </div>
        <div class="form-group">
          {{ form.category.errors }}
          <label for="category">Category:</label>
          {{ form.category }}
        </div>
        <div class="form-group">
          {{ form.text.errors }}
          <label for="id_sender">Text:</label>
          {{ form.text }}
        </div>
        <div class="form-group">
          {{ form.image.errors }}
          <label for="id_sender">Image:</label>
          {{ form.image }}
        </div>
        <button type="submit" class="btn btn-primary">Save</button>
      </form>
    </div>
  </div>
{% endblock place_article %}

blog/templates/blog/article_list.html
{% extends 'blog/content.html' %}

{% block place_article %}
  <h1 class="mt-4"></h1>

  <!-- Search input -->
  {% ifequal mode_list "search" %}
    <div class="card my-4">
      <h5 class="card-header">Search results</h5>
      <div class="card-body">
        <div class="input-group" >
          <div class="col-12">
            <form method="GET" class="form-inline" action="{% url 'blog:search_list'  %}">
              <input type="text" class="form-control"  name="srchtxt" placeholder="Search for..." value="{{ srchtxt }}" >
              <span class="input-group-btn">
                <button class="btn btn-secondary" type="submit">Go!</button>
              </span>
            </form>
          </div>
        </div>
      </div>
    </div>
  {% endifequal %}

  <!-- List articles -->
  {% if list_article_pag %}
    <div id="update-list">
    {% for article in list_article_pag %}
      <input type="text" size="40" value="{{ article.pk }}" name="{{ article.pk }}" class="id-article">
      <div class="card mb-4">
        {% if article.image %}
          <div class="span2">
            <img  src="{{ MEDIA_URL }}{{ article.image }}">
          </div>
        {% endif %}
        <div class="card-body">
          <h2 class="card-title">{{ article.title }}</h2>
          <p class="card-text">{% autoescape off %}{{ article.text|striptags|linebreaksbr|truncatechars:400 }}{% endautoescape %}</p>
          <a href="{% url 'blog:article_detail' pk=article.pk %}" class="btn btn-primary">Read More &rarr;</a>
        </div>
        <div class="card-footer text-muted">
          {% ifequal mode_list "draft" %}
            created: {{ article.created_date|date:'d-m-Y' }} by
          {% else %}
            {{ article.published_date|date:'d-m-Y' }} by
          {% endifequal %}
          <a href="{% url 'blog:article_author_list' authorName=article.author.username %}">{{ article.author }}</a>
          Categories: <a href="{% url 'blog:article_categories_list' categoryName=article.category.urlstext %}">{{ article.category }}</a> Comments: {{ article.approved_comments.count }}
        </div>
      </div>
    {% endfor %}
    </div>
  {% else %}
    <p>No blog are available.</p>
  {% endif %}

  <!-- Pagination -->
  {% if is_paginated  %}
    <div id="paginated">
    <ul class="pagination justify-content-center mb-4">
      {% if page_obj.has_previous %}
        {% ifequal mode_list "search" %}
          <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}&srchtxt={{ srchtxt }}">&laquo;</a></li>
        {% else %}
          <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
        {% endifequal %}
      {% else %}
        <li class="page-item disabled"><span class="page-link">&laquo;</span></li>
      {% endif %}
      {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span></li>
        {% else %}
          {% ifequal mode_list "search" %}
            <li class="page-item"><a class="page-link" href="?page={{ i }}&srchtxt={{ srchtxt }}">{{ i }}</a></li>
          {% else %}
            <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
          {% endifequal %}
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        {% ifequal mode_list "search" %}
          <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}&srchtxt={{ srchtxt }}">&raquo;</a></li>
        {% else %}
          <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
        {% endifequal %}
      {% else %}
        <li class="page-item disabled"><span class="page-link">&raquo;</span></li>
      {% endif %}
    </ul>
    </div>
  {% endif %}

{% endblock place_article %}

blog/templates/blog/comment_confirm_delete.html
{% extends 'blog/content.html' %}

{% block place_article %}
  <div class="card my-4">
    <h5 class="card-header">Delete Comment:</h5>
    <div class="card-body">
      <form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <input type="button" class="btn btn-primary" value="Cancel" onClick="javascript:history.go(-1);">&nbsp;&nbsp;

        <button type="submit" class="btn btn-primary">Confirm</button>
      </form>
    </div>
  </div>
{% endblock place_article %}

blog/templates/blog/content.html
{% extends 'blog/index.html' %}

{% load collection_extras %}

{% block content %}
<div class="container">
  <div class="row">
    <!-- Blog Entries Column -->
    <div class="col-lg-8">
      <!-- Blog Article -->
      {% block place_article %}
      {% endblock %}
    </div>

    <!-- Sidebar Widgets Column -->
    <div class="col-lg-4">
      <!-- Search Widget -->
      <div class="card my-4">
        <h5 class="card-header">Search</h5>
        <div class="card-body">
          {% get_widgets_search %}
        </div>
      </div>

      <!-- Categories Widget -->
      <div class="card my-4">
        <h5 class="card-header">Categories</h5>
        <div class="card-body">
          {% get_widgets %}
        </div>
      </div>

      <!-- Side Widget -->
      <div class="card my-4">
        <h5 class="card-header">Calendar</h5>
        <div class="card-body">
          {% get_widgets_calendar %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

blog/templates/blog/footer.html
<footer class="py-5 bg-dark">
  <div class="container">
    <p class="m-0 text-center text-white">Copyright &copy; Django My Blog 2017</p>
  </div>
</footer>

blog/templates/blog/navigation.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container">
    <a class="navbar-brand" href="/">Django My Blog</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:article_new' %}">
              <span class="glyphicon glyphicon-plus"></span>&nbsp;New
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:article_draft_list' %}">
              <span class="glyphicon glyphicon-edit"></span>&nbsp;Draft
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">
              <span class="glyphicon glyphicon-log-out"></span>&nbsp;({{ user.username }}&nbsp;Log out)
            </a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:register' %}">
              <span class="glyphicon glyphicon-edit"></span>&nbsp;Registration
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">
              <span class="glyphicon glyphicon-log-in"></span>&nbsp;Login
            </a>
          </li>
        {% endif %}
        <li class="nav-item active">
          <a class="nav-link" href="/">Home
            <span class="sr-only">(current)</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'aboutblog:about' %}">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/admin">Services</a>
        </li>
      </ul>
    </div>
  </div>
</nav>